-- libmarpa binding
local lib   = require 'libmarpa'
local C     = lib.C
local ffi   = lib.ffi

-- components
local grammar = require 'grammar'
local recognizer = require 'recognizer'
local valuator = require 'valuator'

return {

  libmarpa = libmarpa,
  grammar = grammar,
  recognizer = recognizer,
  valuator = valuator,

  PROPER_SEPARATION = C.MARPA_PROPER_SEPARATION,
  KEEP_SEPARATION = C.MARPA_KEEP_SEPARATION,

  STEP_RULE = C.MARPA_STEP_RULE,
  STEP_TOKEN = C.MARPA_STEP_TOKEN,
  STEP_NULLING_SYMBOL = C.MARPA_STEP_NULLING_SYMBOL,
  STEP_TRACE = C.MARPA_STEP_TRACE,
  STEP_INACTIVE = C.MARPA_STEP_INACTIVE,
  STEP_INITIAL = C.MARPA_STEP_INITIAL,

  EVENT_NONE = C.MARPA_EVENT_NONE,
  EVENT_COUNTED_NULLABLE = C.MARPA_EVENT_COUNTED_NULLABLE,
  EVENT_EARLEY_ITEM_THRESHOLD = C.MARPA_EVENT_EARLEY_ITEM_THRESHOLD,
  EVENT_EXHAUSTED = MARPA_EVENT_EXHAUSTED,
  EVENT_LOOP_RULES = MARPA_EVENT_LOOP_RULES,
  EVENT_NULLING_TERMINAL = MARPA_EVENT_NULLING_TERMINAL,
  EVENT_SYMBOL_COMPLETED = MARPA_EVENT_SYMBOL_COMPLETED,
  EVENT_SYMBOL_EXPECTED = MARPA_EVENT_SYMBOL_EXPECTED,
  EVENT_SYMBOL_NULLED = MARPA_EVENT_SYMBOL_NULLED,
  EVENT_SYMBOL_PREDICTED = MARPA_EVENT_SYMBOL_PREDICTED,

}
